# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aareguru < Formula
  desc "aare.guru Aaretemperatur & Wetter & Sonne fürs Aareschwimmen - Chills mau wider chli"
  homepage "https://aare.guru/"
  version "0.5.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gexclaude/aaregurucli/releases/download/v0.5.0/aareguru_0.5.0_darwin_amd64.tar.gz"
      sha256 "ee67f405236a1b9227cd941799803aa4276e19307b307facd88eaf7ac9a8fa31"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gexclaude/aaregurucli/releases/download/v0.5.0/aareguru_0.5.0_linux_amd64.tar.gz"
      sha256 "2490db404ed191002ba38e76131bf134a798e5672a67fe6db9632e6a82f47d10"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gexclaude/aaregurucli/releases/download/v0.5.0/aareguru_0.5.0_linux_armv6.tar.gz"
      sha256 "9126b436a107cb175d9912f9b99c0f84b3c69b18cf556b92cf40afd67a65afbb"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gexclaude/aaregurucli/releases/download/v0.5.0/aareguru_0.5.0_linux_arm64.tar.gz"
      sha256 "d3cb4cab981baf88d660b2a0ab68525ae53509da5802eca4ac6bca5074732e6a"
    end
  end

  def install
    bin.install "aareguru"
  end
end
